import Logo from "./components/Logo";
import Navigation from "./components/Navigation";
import "@/app/_styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
          <Navigation />
        </header>
        {children}
        <main></main>
        <footer>some dome copyright@1</footer>
      </body>
    </html>
  );
}
